### ISSUE TITLE
Bug in profile popup for anonymous users

### ISSUE THREAD

**Issue by amitpant14** [2KAbhishek/Byteblog#1]
For anonymous users, on hovering over a username, the popup displays the login form. Here is the screenshot of the same.
![image](https://user-images.githubusercontent.com/50552215/106642402-50d84e00-65ae-11eb-95ba-8d6d75c15833.png)
Also, the popup does not disappear after that.

**Comment by 2KAbhishek** [comment]
Thanks for letting me know, I'll fix it soon.

**Comment by amitpant14** [comment]
Okay.
